export const chairs = [
  {
    status: "New",
    pic: "/chairs_trend/Minimal_LCD.png",
    product: "CHAIR",
    name: "Minimal LCD chair",
    price_discount: "$180",
    price: "$250",
    rating: 5,
  },
  {
    status: "New",
    pic: "/chairs_trend/Minimal_iconic.png",
    product: "CHAIR",
    name: "Minimal iconic chair",
    price_discount: "$120",
    price: "$150",
    rating: 4,
  },
  {
    status: "Sale",
    pic: "/chairs_trend/Dining.png",
    product: "CHAIR",
    name: "Dining chairs",
    price_discount: "$100",
    price: "$120",
    rating: 5,
  },
  {
    status: "Sale",
    pic: "/chairs_trend/Buskbo_armchair.png",
    product: "CHAIR",
    name: "Buskbo armchair ",
    price_discount: "$130",
    price: "$150",
    rating: 4,
  },
  {
    status: "Sale",
    pic: "/chairs_trend/Modern_chair.png",
    product: "CHAIR",
    name: "Modern chair",
    price_discount: "$100",
    price: "$120",
    rating: 0,
  },
  {
    status: "Sale",
    pic: "/chairs_trend/Plastic_dining_chair.png",
    product: "CHAIR",
    name: "Plastic dining chair",
    price_discount: "$130",
    price: "$250",
    rating: 4,
  },
  {
    status: "New",
    pic: "/chairs_trend/Minimal_Wood_chair.png",
    product: "CHAIR",
    name: "Minimal Wood chair",
    price_discount: "$180",
    price: "$250",
    rating: 5,
  },
  {
    status: "New",
    pic: "/chairs_trend/Elegant_wood_chair.png",
    product: "CHAIR",
    name: "Elegant wood chair",
    price_discount: "$180",
    price: "$250",
    rating: 5,
  },
];
